# Generated by Django 4.2 on 2024-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('women', "Women's Wear"), ('men', "Men's Wear"), ('baby', 'Baby Wear')], max_length=50, null=True),
        ),
    ]
